apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  labels:
    app: ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ["sleep", "123456"]
        securityContext:
          runAsUser: 1000  # Specify a non-root user
          runAsGroup: 1000 # Specify a non-root group
          runAsNonRoot: true  # Ensure the container doesn't run as root
          allowPrivilegeEscalation: false  # Disallow privilege escalation
      nodeSelector:
        beta.kubernetes.io/os: linux