name: 'AKS Deployment/Destroy with Terraform Script'

#on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Terraform Init'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        run: terraform init
        #run: |
        #  ter  raform init \
        #    -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
        #    -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
        #    -backend-config="key=terraform.tfstate" \
        #    -backend-config="access_key=${{ secrets.AZURE_STORAGE_ACCESS_KEY }}"

      - name: 'Terraform Plan'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        run: terraform plan -var="resource_group_name=jl-aks-rg" -var="location=Southeast Asia" -var="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -var="container_name=${{ secrets.CONTAINER_NAME }}"

      #- name: 'Terraform Apply'
      #  env:
      #    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #    ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      #    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #    ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
      #  if: github.ref == 'refs/heads/main'
      #  run: terraform apply -auto-approve -var="resource_group_name=jl-aks-rg" -var="location=Southeast Asia" -var="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -var="container_name=${{ secrets.CONTAINER_NAME }}"

      - name: 'Terraform Destroy'
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        if: github.ref == 'refs/heads/main'
        run: terraform destroy -auto-approve -var="resource_group_name=jl-aks-rg" -var="location=Southeast Asia" -var="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" -var="container_name=${{ secrets.CONTAINER_NAME }}"
