name: Scan Repo to see vulnerabilities

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout SCM from Github
        uses: actions/checkout@v4
      -
        name: Perform FortiDevSec (SAST SCAN)
        run: |
         env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
         docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
         docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      -
        name: Perform FortiDevSec (DAST SCAN)
        run: |
         env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
         docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
         docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
