name: Scan Repo to see vulnerabilities

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout SCM from Github
        uses: actions/checkout@v4
      #-
      #  name: Perform FortiDevSec (SAST SCAN)
      #  run: |
      #   env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
      #   docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      #   docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
      #-
      #  name: Perform FortiDevSec (DAST SCAN)
      #  run: |
      #   env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
      #   docker pull registry.fortidevsec.forticloud.com/fdevsec_dast:latest
      #   docker run --rm --env-file /tmp/env --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_dast:latest
      - 
        name: DAST_PROXY_SERVER
        run: |
            export EMAIL=ljawn@fortinet.com LICENSE_SERIAL=FDEVSC0000000689_0691BM801347 ASSET_TOKEN=6JfrmTmMbQjqPmrM9TsLtDgDtV9jTOWsMUaqwGwhYjJvYq1rtgSz5uJ5/cLlnK1D27TM6/DcjPLZb4G7wGaWCgjvkjvtH+KrJlgXvQ== SCANURL=http://10.0.0.220:8000 SCANTYPE=1 ASSET=58d059ca-5f2c-48ae-aee3-54a0c4ff6642
            env | grep -E "EMAIL|LICENSE_SERIAL|ASSET_TOKEN|SCANURL|SCANTYPE|ASSET" > /tmp/env
            docker pull registry.fortidast.forticloud.com/dastdevopsproxy:latest
            docker run --rm --env-file /tmp/env --network=host registry.fortidast.forticloud.com/dastdevopsproxy:latest