name: GKE Deployment with Bash Script

on:
  push:
    branches:
      - main

jobs:
  create-gke:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        PROJECT_ID: "ljawn-se-lab"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #env:
      #  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      #  run: echo "$GCP_SERVICE_ACCOUNT_KEY" | gcloud auth activate-service-account --key-file=-

    - name: Run GKE creation script
      run: bash gke-bash-new.sh
      #env:
      #  GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCLOUD_SERVICE_KEY }}
    
    #- name: Print decoded service account keyz
    #  run: |
    #    echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" | base64 --decode > ${HOME}/gcloud-service-key.json
    #    cat ${HOME}/gcloud-service-key.json
    #  env:
    #    GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCLOUD_SERVICE_KEY }}


    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID
      env:
        PROJECT_ID: "ljawn-se-lab"
        CLUSTER_NAME: "jl-gke-sg"
        ZONE: "asia-southeast1-a" # Replace with your chosen zone

    - name: Display kubeconfig
      run: |
        echo "Kubeconfig:"
        cat ~/.kube/config
