name: push image to docker hub
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout SCM from Github
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Pull MariaDB Image
        run: docker pull mariadb:10.6.2

      - name: Build Docker image without cache
        run: docker build --no-cache -t verademo ./verademo
      
      - name: Push Docker image to Docker Hub
        run: docker push verademo